Feat/new days donating
RibonDAO/core-api pull request #1407
Opened 2024-05-17 14:10 UTC by dapeduu

Adds a new field to user donation stats, and a new job to increment the days donating field on each donation.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How to test

- Run the AddToDaysDonatingJob
  - Check if it only increments days donating if there wasnt a donation on the same day

2024-05-21 13:04 UTC, thaisribon commented on Gemfile
> +  # gem 'ruby-lsp', '~> 0.3.6', require: false
I think you forgot to remove the comment

2024-05-21 13:04 UTC, thaisribon commented on app/jobs/users/update_days_donating_for_all_job.rb
> +        last_user = update_list.keys.last
this update_list.keys.last would not be the user_donation_stats id ? I think here you need the user_id, right?

2024-05-21 13:04 UTC, thaisribon commented on app/jobs/users/update_days_donating_for_all_job.rb
> +    def user_batches(&)
what does & do?

2024-05-21 13:04 UTC, thaisribon commented on config/schedule.yml
> +  class: "Users::UpdateDaysDonatingForAllJob"
It has to be a Worker, so you need to create a worker that calls the job

2024-05-21 19:15 UTC, dapeduu commented on Gemfile
> +  # gem 'ruby-lsp', '~> 0.3.6', require: false
Acctually in the docs they say that we shouldnt include the gem directly, instead we can just install the extension and everything should work. It also installs the latest version, which is 0.16 by now. 

![image](https://github.com/RibonDAO/core-api/assets/57116106/b2145735-c1b9-4361-8bb0-43d75ecd7396)

I think it would be nice to remove it from there, what do you think?

2024-05-21 19:19 UTC, dapeduu commented on app/jobs/users/update_days_donating_for_all_job.rb
> +        last_user = update_list.keys.last
The function that creates the update_list uses the index_by, which creates an set where the key is the user_id. So here we can use the keys to get the last user id. 

![image](https://github.com/RibonDAO/core-api/assets/57116106/ba6da65e-d4d8-4133-8287-3396208a7a53)

But still, I should probably change it to be more legible.

2024-05-21 19:21 UTC, dapeduu commented on app/jobs/users/update_days_donating_for_all_job.rb
> +    def user_batches(&)
It is a block, thanks to it we can pass a block to the function in the format in the photo. So basically it is exchanged by the block I pass to the function.

![image](https://github.com/RibonDAO/core-api/assets/57116106/9c83b2ca-f0e5-44b9-99f9-8f1582aeaaeb)

2024-05-21 19:24 UTC, dapeduu commented on app/jobs/users/update_days_donating_for_all_job.rb
> +    def user_batches(&)
This link has some examples: https://reintech.io/blog/how-to-use-ruby-blocks

I just learned that I can name the block. Ill do it so it is more legible

2024-05-22 19:39 UTC, dapeduu commented on config/schedule.yml
> +  class: "Users::UpdateDaysDonatingForAllJob"
Done!

2024-06-03 19:17 UTC, leodhb requested changes

2024-06-03 19:17 UTC, leodhb commented on app/jobs/users/update_days_donating_for_all_job.rb
> +    REDIS_KEY = 'last_updated_user_id'.freeze
What do you think about rename it to LAST_UPDATE_USER_ID_KEY?

We have a convention to use more specific variable names in these cases.

2024-06-03 19:17 UTC, leodhb commented on app/services/user_services/statistics.rb
> +    def user_days_donating
Can we rename it to just `days_donating`? This service is already user scoped. It will allow us to use the shorthand hash syntax on line 51.

2024-06-03 19:17 UTC, leodhb commented on Gemfile
> +  # gem 'ruby-lsp', '~> 0.3.6', require: false
Nice catch. A formed dev was used to code using rubymine. but currently all of us are using vscode.

2024-06-04 19:47 UTC, dapeduu commented on app/services/user_services/statistics.rb
> +    def user_days_donating
its a lot better now! 😄 
Done!

2024-06-04 19:47 UTC, dapeduu commented on app/jobs/users/update_days_donating_for_all_job.rb
> +    REDIS_KEY = 'last_updated_user_id'.freeze
Done!

2024-06-05 14:30 UTC, thaisribon approved these changes

2024-06-05 14:39 UTC, leodhb approved these changes
Looking great 🚀

2024-06-05 15:03 UTC, merged