Feat/dapp 659
RibonDAO/core-api pull request #537
Opened 2023-01-16 19:34 UTC by letbueno

# Description

- A brief description of the feature/fix

# Necessary changes

- Put here any changes that must be done when this PR is merged
- eg: update an environment variable

## Does this pull request close any open issues?

- Put here the issue that must be closed with this PR
- eg: closes [#001]()

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dangerous changes
- [ ] Chore (change that does not effect how the code works, eg: change color)
- [ ] Tests

## How to test

Put here all the things need to test this PR and verify your changes, also list any relevant details for tests (eg: have a wallet)

- Test A

2023-01-16 20:06 UTC, leodhb requested changes

2023-01-16 20:06 UTC, leodhb commented on app/models/non_profits/non_profit.rb
> +
NonProfitImpacts is N:1 to NonProfits. There's a way to do the exact same thing here (getter and setters for 1:N) using delegate?

2023-01-16 20:06 UTC, leodhb commented on db/seeds.rb
> -  non_profit = FactoryBot.create(:non_profit, :with_impact) if NonProfit.count.zero?
NOTE: Now every nonprofit created by a factory has also a NonProfitImpact, it's cheaper to add :with_impact to more than 100 test cases. And for me is a better way to build a nonProfit entity

2023-01-17 11:42 UTC, NickNish09 commented on app/models/non_profits/non_profit.rb
> +    non_profit_impacts&.first&.impact_description
Shouldn't this one be non_profit_impacts.last? Since the last one we create shoud be tha main one.
Or we could create a `main_impact` method that returns the non_profit_impacts.last

2023-01-17 11:42 UTC, NickNish09 commented on db/migrate/20230116173221_move_impact_description_to_non_profit_impacts.rb
> +end
is this necessary to be in a migration? Maybe we could first of all create the `impact_description` field on the `non_profit_impact`, then clone all the impact fields to it, and then we can drop the `non_profits.impact_description` column. What do you think?

2023-01-17 13:54 UTC, leodhb commented on app/models/non_profits/non_profit.rb
> +    non_profit_impacts&.first&.impact_description
FIXED

2023-01-17 14:28 UTC, closed without merging